### ISSUE TITLE
Compatibility: Sucrose Wallpaper Engine 

### ISSUE THREAD

**Issue by Taiizor** [IPdotSetAF/NeoMatrix#15]
First of all, this is the best Matrix theme I've seen so far. I really appreciate your work. As soon as I saw it, I immediately adapted it for my own application.

[Neo Matrix-1.zip](https://github.com/IPdotSetAF/NeoMatrix/files/15438939/Neo.Matrix-1.zip)

![Sucrose-Neo-Matrix](https://github.com/IPdotSetAF/NeoMatrix/assets/41683699/f30e0c4d-f7a7-4543-8d2e-5f441ee4fabb)
![Sucrose-Neo-Matrix](https://github.com/IPdotSetAF/NeoMatrix/assets/41683699/80170a86-7b83-4460-a19b-6548ab7bc4ef)
![Sucrose-Neo-Matrix](https://github.com/IPdotSetAF/NeoMatrix/assets/41683699/0c9fdaf2-af99-4c55-8780-edaaf4dace3b)

**Comment by IPdotSetAF** [comment]
Thanks man, I'm happy to hear that.
OMG, I have seen Sucrose few days ago, but i couldn't imagine such a fast adoption, nice job.

I would love to make the wallpaper compatible with another engine, It would be great to merge ur changes to the NeoMatrix Repo.
I'll check out ur code and let u know.
