### ISSUE TITLE
Design of Logo/Favicon

### ISSUE THREAD

**Issue by Taiizor** [IPdotSetAF/NeoMatrix#19]
I created a few drawings using AI below. If there is any you like, I will convert it to the ICO format and add it to the project.

<img src="https://github.com/IPdotSetAF/NeoMatrix/assets/41683699/d25b6d96-8384-420c-8c38-7dadf8761242" width=96px/>
<img src="https://github.com/IPdotSetAF/NeoMatrix/assets/41683699/8e5b426e-dfc3-4a2d-825e-97f2546525dc" width=96px/>
<img src="https://github.com/IPdotSetAF/NeoMatrix/assets/41683699/80d35d70-5ebf-47fc-9a57-668606622ddb" width=96px/>
<img src="https://github.com/IPdotSetAF/NeoMatrix/assets/41683699/38eb5334-4590-4e4c-880f-79ff454f3ee3" width=96px/>
<img src="https://github.com/IPdotSetAF/NeoMatrix/assets/41683699/129fb58f-50b6-43bd-a396-0fde57dd1211" width=96px/>
<img src="https://github.com/IPdotSetAF/NeoMatrix/assets/41683699/54715361-95ca-4e41-aa83-6acef86ae499" width=96px/>
<img src="https://github.com/IPdotSetAF/NeoMatrix/assets/41683699/d7c78494-8c66-4e0b-879e-04f71497dd42" width=96px/>
<img src="https://github.com/IPdotSetAF/NeoMatrix/assets/41683699/e5f18fe0-fdd5-441a-8243-14f7dabea5e3" width=96px/>
<img src="https://github.com/IPdotSetAF/NeoMatrix/assets/41683699/abab1165-4ecc-474a-b93b-46dbb96639e0" width=96px/>
<img src="https://github.com/IPdotSetAF/NeoMatrix/assets/41683699/798a1f83-6694-44bd-8e26-4997afce445e" width=96px/>
<img src="https://github.com/IPdotSetAF/NeoMatrix/assets/41683699/00292c02-ab4a-4f7a-8b75-98711b7c9828" width=96px/>
<img src="https://github.com/IPdotSetAF/NeoMatrix/assets/41683699/f7a1a624-b0e2-4df2-9e26-60a0088e738f" width=96px/>
<img src="https://github.com/IPdotSetAF/NeoMatrix/assets/41683699/b193f278-b7b8-412c-9da8-2538fafd445a" width=96px/>

My favorites:

<img src="https://github.com/IPdotSetAF/NeoMatrix/assets/41683699/8e5b426e-dfc3-4a2d-825e-97f2546525dc" width=96px/>
<img src="https://github.com/IPdotSetAF/NeoMatrix/assets/41683699/abab1165-4ecc-474a-b93b-46dbb96639e0" width=96px/>

**Comment by IPdotSetAF** [comment]
![](https://private-user-images.githubusercontent.com/41683699/333875060-f7a1a624-b0e2-4df2-9e26-60a0088e738f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MzI5OTUsIm5iZiI6MTcxNjczMjY5NSwicGF0aCI6Ii80MTY4MzY5OS8zMzM4NzUwNjAtZjdhMWE2MjQtYjBlMi00ZGYyLTllMjYtNjBhMDA4OGU3MzhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDE0MTEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkOWUyNjgyNGY0OGE2MWJkY2E5YmMyODkzMzFlMGNhZTk2ZjNhYTg0YWJjMDdjMjQyOTIzZWFiZTYwYmE0MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.67p8_pIVeM8ABL6qIb-6lH5z3VsIQNSdCs4_30wttr0)

![](https://private-user-images.githubusercontent.com/41683699/333874867-38eb5334-4590-4e4c-880f-79ff454f3ee3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MzI5OTUsIm5iZiI6MTcxNjczMjY5NSwicGF0aCI6Ii80MTY4MzY5OS8zMzM4NzQ4NjctMzhlYjUzMzQtNDU5MC00ZTRjLTg4MGYtNzlmZjQ1NGYzZWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDE0MTEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5YTYxMDJkMzY2ZTkzNjQ3YTE3MzVkZGYxYmMwMTZlMWM2NTZkNWI4NGUwMzZiM2M5ZWU0ZTBjYTBhYWNhZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mtwwN71zMPOijzmJS-F0iLw9QumYAPa_ZYXTGRy6Uyw)

I like these two more, I think the guy with umbrella doesn't fit the purpose, and i'm afraid the triangle symbol might accidentally represent som cult 😄

**Comment by Taiizor** [comment]
> ![](https://private-user-images.githubusercontent.com/41683699/333875060-f7a1a624-b0e2-4df2-9e26-60a0088e738f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MzI5OTUsIm5iZiI6MTcxNjczMjY5NSwicGF0aCI6Ii80MTY4MzY5OS8zMzM4NzUwNjAtZjdhMWE2MjQtYjBlMi00ZGYyLTllMjYtNjBhMDA4OGU3MzhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDE0MTEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkOWUyNjgyNGY0OGE2MWJkY2E5YmMyODkzMzFlMGNhZTk2ZjNhYTg0YWJjMDdjMjQyOTIzZWFiZTYwYmE0MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.67p8_pIVeM8ABL6qIb-6lH5z3VsIQNSdCs4_30wttr0)
> 
> ![](https://private-user-images.githubusercontent.com/41683699/333874867-38eb5334-4590-4e4c-880f-79ff454f3ee3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MzI5OTUsIm5iZiI6MTcxNjczMjY5NSwicGF0aCI6Ii80MTY4MzY5OS8zMzM4NzQ4NjctMzhlYjUzMzQtNDU5MC00ZTRjLTg4MGYtNzlmZjQ1NGYzZWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDE0MTEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5YTYxMDJkMzY2ZTkzNjQ3YTE3MzVkZGYxYmMwMTZlMWM2NTZkNWI4NGUwMzZiM2M5ZWU0ZTBjYTBhYWNhZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mtwwN71zMPOijzmJS-F0iLw9QumYAPa_ZYXTGRy6Uyw)
> 
> I like these two more, I think the guy with umbrella doesn't fit the purpose, and i'm afraid the triangle symbol might accidentally represent som cult 😄

Oops, you might be right (: But I can't see which two you like o_O

![I-Cant-See](https://github.com/IPdotSetAF/NeoMatrix/assets/41683699/143b4b6d-3841-41ce-ab0c-f8713565373d)
